# Generated by Django 4.1.2 on 2022-11-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', models.TextField(verbose_name='selected_value')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constraints.constraint')),
            ],
        ),
        migrations.AddField(
            model_name='constraint',
            name='constraint_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constraints.constrainttype'),
        ),
    ]
