# Generated by Django 4.1.2 on 2022-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0002_alter_constraintassociation_selected_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraintassociation',
            name='name',
            field=models.CharField(default='ConstraintAssociationObject', max_length=200),
        ),
    ]
