# Generated by Django 4.1.2 on 2022-11-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_control_name'),
        ('assets', '0004_asset_properties'),
        ('constraints', '0004_constraintassociation_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraintassociation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='constraintassociation',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.control'),
        ),
    ]
