# Generated by Django 4.1.1 on 2022-10-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='assettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettype'),
        ),
    ]
