# Generated by Django 4.1.2 on 2022-12-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_control_name'),
        ('assets', '0004_asset_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetControlMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.control')),
            ],
        ),
    ]
