# Generated by Django 4.1.1 on 2022-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_parent_propertie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='parent_propertie',
            new_name='parent_property',
        ),
    ]
