# Generated by Django 4.1.2 on 2022-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_parent_propertie_property_parent_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property_keywords', models.TextField(verbose_name='property_keywords')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_tags',
            field=models.ManyToManyField(blank=True, to='properties.propertytag'),
        ),
    ]
