# Generated by Django 4.1.2 on 2022-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertytag_property_property_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertytag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
