# Generated by Django 4.1.2 on 2022-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keywords_counter', models.IntegerField()),
                ('tags_counter', models.IntegerField()),
                ('keyword_cluster_distributions', models.JSONField()),
                ('control_cluster_distributions', models.JSONField()),
                ('average_keyword_per_tag', models.IntegerField()),
                ('average_controls_per_tag', models.IntegerField()),
            ],
        ),
    ]
