# Generated by Django 4.1.2 on 2022-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_average_keyword_per_tag_metric_average_keywords_per_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='matched_control_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='matched_tags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='matching_tag_distribution',
            field=models.IntegerField(default=0),
        ),
    ]
