# Generated by Django 4.1.2 on 2022-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metric_matched_control_count_metric_matched_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='matching_tag_distribution',
            field=models.JSONField(),
        ),
    ]
