# Generated by Django 4.1.2 on 2022-12-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_metric_matching_tag_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='other_metrics',
            field=models.JSONField(default={}),
        ),
    ]
