# Generated by Django 4.1.2 on 2022-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_metric_other_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='other_metrics',
            field=models.JSONField(),
        ),
    ]
