# Generated by Django 4.1.4 on 2023-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_alter_metric_other_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='deleted_clusters',
            field=models.IntegerField(default=0),
        ),
    ]
