# Generated by Django 4.1.2 on 2022-10-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
