# Generated by Django 4.1.2 on 2022-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('controls', '0002_alter_control_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='tags',
        ),
        migrations.AddField(
            model_name='control',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
