# Generated by Django 4.1.2 on 2022-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_control_tags_control_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
